cabal-version:        2.4
name:                 md-bench
version:              0.0.1.0
tested-with:          GHC==9.10.3
license:              BSD-3-Clause
license-file:         LICENSE.md
author:               Mark Karpov <markkarpov92@gmail.com>
maintainer:           Mark Karpov <markkarpov92@gmail.com>
homepage:             https://github.com/mrkkrp/md-bench
bug-reports:          https://github.com/mrkkrp/md-bench/issues
category:             Text
synopsis:             Benchmark comparing Haskell markdown libraries
build-type:           Simple
description:          Benchmark comparing Haskell markdown libraries.
extra-doc-files:      README.md
data-files:           data/README.md

source-repository head
  type:               git
  location:           https://github.com/mrkkrp/md-bench.git

library
  hs-source-dirs:     src
  build-depends:      base
                    , blaze-html
                    , cmark
                    , commonmark
                    , lucid
                    , mmark
                    , pandoc
                    , text
  exposed-modules:    MD
  ghc-options:        -O2 -Wall
  default-language:   GHC2021

executable md-bench
  main-is:            Main.hs
  hs-source-dirs:     app
  build-depends:      base
                    , md-bench
                    , text
  ghc-options:        -O2 -Wall
  default-language:   GHC2021

benchmark bench-speed
  main-is:            Main.hs
  hs-source-dirs:     bench/speed
  type:               exitcode-stdio-1.0
  build-depends:      base
                    , criterion
                    , text
                    , deepseq
                    , md-bench
  ghc-options:        -O2 -Wall
  default-language:   GHC2021

benchmark bench-memory
  main-is:            Main.hs
  hs-source-dirs:     bench/memory
  type:               exitcode-stdio-1.0
  build-depends:      base
                    , deepseq
                    , text
                    , weigh
                    , md-bench
  ghc-options:        -O2 -Wall
  default-language:   GHC2021
